import dda_model
from dda_model import optimizers
from dda_model import binarizers

from vizier.service import clients as vz_clients
from vizier.service import pyvizier as vz

from itertools import product as iter_product

import numpy as np
import json
from pathlib import Path
import os
import shutil
import sys
from scipy.signal import convolve2d
from scipy import ndimage

import matplotlib.pyplot as plt
import plotting


def _constructModel():

    model = dda_model.DDAModelWrapper(
        geometry_shape,
        pixel_size,
        initialization,
        dielectric_constants=dielectric_constants,
        light_direction=light_direction,
        light_polarization=light_polarization,
        light_wavelength_nm=wavelength,
        symmetry_axes=sym_axis,
        verbose=False,
    )
    return model

def _saveObjective(all_obj, path):
    curr_path = os.path.join(path, "Obj.txt")
    np.savetxt(curr_path, all_obj, delimiter='\n')

def _saveBetas(all_betas, path):
    curr_path = os.path.join(path, "betas.txt")
    np.savetxt(curr_path, all_betas, delimiter='\n')

def _saveFilterRadii(all_radii, path):
    curr_path = os.path.join(path, "filter_radii.txt")
    np.savetxt(curr_path, all_radii, delimiter='\n')

def _saveCurrentStructure(all_parameters, path, iteration):
    curr_path = os.path.join(path, "Structures", f"Structure{iteration}.npy")
    np.save(curr_path, all_parameters)

def _saveCurrentEField(electric_field, path, iteration):
    curr_path = os.path.join(path, f"E-Fields", f"E-Field{iteration}.npy")
    np.save(curr_path, electric_field)

def _saveAllParams(params, path, iteration):
    curr_path = os.path.join(path, "Parameters", f"Param{iteration}.npy")
    np.save(curr_path, params)

def _saveParamsBeforeThreshold(params, path, iteration):
    curr_path = os.path.join(path, "Parameters_Before_Threshold", f"Param{iteration}.npy")
    np.save(curr_path, params)

def _createDirectories(path):
    directories = ['Structures', 'Parameters', 'Parameters_Before_Threshold', 'E-Fields']
    for directory in directories:
        Path(os.path.join(path, directory)).mkdir(parents=True, exist_ok=True)

def _calculateBeta(iteration, beta_type):
    match beta_type:
        case 'piecewise':
            return binarizers.piecewise_update(iteration, beta_config)
        case 'piecewise_absolute':
            return binarizers.piecewise_update_absolute(iteration, beta_config)
        case 'linear':
            return binarizers.linear_update(iteration, beta_config)
        case 'exp':
            return binarizers.exp_update(iteration, beta_config)
        case 'constant':
            return beta_config["beta_const"]

def _saveStepSizes(all_step_sizes, path):
    curr_path = os.path.join(path, "stepsizes.txt")
    np.savetxt(curr_path, all_step_sizes, delimiter='\n')

def closed_range(start, stop):
    return range(start, stop + 1)

# CODE STARTS HERE!!!
json_file = sys.argv[1]
with open(json_file) as user_file:
    parsed_json = json.load(user_file)

sym_axis = parsed_json["sym_axis"]
geometry_shape = parsed_json["geometry_shape"]
pixel_size = parsed_json["pixel_size"]
light_direction = parsed_json["light_direction"]
light_polarization = parsed_json["light_polarization"]
wavelength = parsed_json["wavelength"]
initialization = np.loadtxt(parsed_json["init_path"])
diel_ext = parsed_json["diel_ext"]
diel_mat = parsed_json["diel_mat"]
dielectric_constants = [diel_ext[0] + diel_ext[1]*1j, diel_mat[0], diel_mat[1]*1j]

evo_max_iter = parsed_json["evo_max_iteration"]

base_path = parsed_json["base_path"]
run_name = parsed_json["run_name"]
full_path = os.path.join(base_path, run_name)
print("Saving value to path: " + full_path)
plot_path = os.path.join(full_path, "Plots")
Path(plot_path).mkdir(parents=True, exist_ok=True)



model = _constructModel()
all_objective_values = []

max_vizier_rounds = 50
candidates_per_round = 1

parameter_shape = [11, 11]

last_design_plotted = 0
num_plotted = 0

def vizier_param_dict_to_array(vz_params, parameter_shape):
    ranges = [range(n) for n in parameter_shape]
    array = np.zeros(parameter_shape, dtype=float)
    for indices in iter_product(*ranges):
        index_name = '_'.join([str(n) for n in indices])
        parameter_name = f'value_{index_name}'
        parameter_value = vz_params[parameter_name]
        parameter_value = 0 if parameter_value.lower() == 'false' else 1
        array[indices] = parameter_value
    return array

def remove_islands(array, max_island_size):
    # When I tried vizier, it initially asked for salt+pepper noise and then
    # gave up and output all 1s. But - like genetic algorithms - vizier does not
    # require gradient access, so the design step does not need to be
    # differentiable. We can try enforcing "manufacturability" constraints to
    # the suggestion generated by vizier.
    def padded_morph_op(x, operation):
        # operation: one of ndimage.binary_opening, binary_closing, etc.
        n = max_island_size
        padded = np.pad(x, n, mode='edge')
        output = operation(padded, iterations=n)
        return output.astype(float)[n:-n,n:-n]
    opening = lambda x: padded_morph_op(x, ndimage.binary_opening)
    closing = lambda x: padded_morph_op(x, ndimage.binary_closing)
    return closing(opening(design))

def binary_open(array, num_iterations):
    def padded_morph_op(x, operation):
        # operation: one of ndimage.binary_opening, binary_closing, etc.
        n = num_iterations
        padded = np.pad(x, n, mode='edge')
        output = operation(padded, iterations=n)
        return output.astype(float)[n:-n,n:-n]
    opening = lambda x: padded_morph_op(x, ndimage.binary_opening)
    return opening(design)


def setup_vizier_study(parameter_shape):
    # Algorithm, search space, and metrics.
    study_config = vz.StudyConfig(algorithm='GAUSSIAN_PROCESS_BANDIT')
    # The algorithm keyword can be used to try out different optimizers. A list
    # can be found at: https://github.com/google/vizier/blob/main/vizier/_src/service/policy_factory.py
    # Add a vizier study parameter for every optimizable parameter.
    # This is possibly not the right way to set up this problem but it is the
    # easiest way. But it looks like add_param supports an "index" argument
    # that effectively does the same thing internally, so maybe it is correct.
    ranges = [range(n) for n in parameter_shape]
    for indices in iter_product(*ranges):
        index_name = '_'.join([str(n) for n in indices])
        parameter_name = f'value_{index_name}'
        # We can try configuring this as either bool (categorical) or
        # discrete, which can use different optimizers. Bool may work
        # better, and some algorithms (like BOCS and HARMONICA) are tailored
        # to work on the {0,1} search space. Another option is to do the
        # optimization in a latent probability space and optimize E[perf|probs].
        study_config.search_space.root.add_bool_param(parameter_name)

    study_config.metric_information.append(
        vz.MetricInformation('objective', goal=vz.ObjectiveMetricGoal.MAXIMIZE))
    # Setup client and begin optimization. Vizier Service will be implicitly created.
    study = vz_clients.Study.from_study_config(study_config, owner='kunal', study_id='example2')
    return study

# Set up the study.
study = setup_vizier_study(parameter_shape)
# print(study)
# print(dir(study))
# import sys
# sys.exit()



all_objective_values = []
num_plotted = 0
# Perform the optimization loop.
for iteration in range(evo_max_iter):
    print(f"{'-' * 40}STARTING ITERATION {iteration} {'-' * 40}")
    # print("Objective values:")
    suggestions = study.suggest(count=candidates_per_round)
    for idx, suggestion in enumerate(suggestions):
        vizier_params = suggestion.parameters
        design = vizier_param_dict_to_array(vizier_params, parameter_shape)
        print(design)
        # Optional, might encourage better optimization / behavior though.
        # design = remove_islands(design, max_island_size=1)
        design = binary_open(design, num_iterations=1)
        print(design)
        # Set the model parameters equal to the new parameters.
        model.parameters = design
        # Evaluate the suggestion on the model.
        objective = model.objective()
        # Mark the vizier trial as complete. Note that the measurement name
        # has to match with the one defined earlier when we configured the study.
        suggestion.complete(vz.Measurement({'objective': objective}))
        # Plot the current objective value.
        all_objective_values.append(objective)
        print(f"\t Suggestion {idx}, objective = {objective:.4f}")

        # In the genetic algorithm, we plotted the best design, but for Vizier
        # (to better understand how it work), we'll plot all the designs.
        plotting.plotGeometry(model.allParameters(), pixel_size, plot_path, num_plotted)
        # Hacky way to re-save the plot but with a new title.
        plt.suptitle(f'Round {iteration+1}, Design {idx+1} Obj={objective:.4f}')
        plt.savefig(os.path.join(plot_path, f"Structure{num_plotted}.png"), dpi=100)
        plt.close()
        np.save(os.path.join(plot_path, f"design_{num_plotted}.npy"), design)
        num_plotted += 1

print(all_objective_values)
